### PR TITLE
Filter out illegal searchmoves.

### LINKED ISSUE #899: Illegal searchmoves crash the app
Illegal `searchmoves` crash the app, e.g.

```
uci
position startpos
go infinite searchmoves e2e5
```

### PR DESCRIPTION
**Pull request by Mardak**
r? @borg323 Fix #899 filtering using the new `MakeRootMoveFilter` from #1281

```
Before:

go nodes 2 searchmoves a1a2
Segmentation fault: 11

go nodes 2 searchmoves a1a2 a2a3 a3a4
bestmove a2a3 ponder e7e5


After:

go nodes 2 searchmoves a1a2
error No legal searchmoves.

go nodes 2 searchmoves a1a2 a2a3 a3a4
bestmove a2a3 ponder e7e5
```

### CODE REVIEW

File: src/mcts/search.cc [hunk 1]
```diff
@@ -48,13 +48,24 @@ namespace {
...
+    const auto legal_moves = board.GenerateLegalMoves();
+    searchmoves.erase(std::remove_if(searchmoves.begin(), searchmoves.end(),
+                                     [&legal_moves](auto m) {
+                                       return std::find(legal_moves.begin(),
+                                                        legal_moves.end(),
+                                                        m) == legal_moves.end();
+                                     }),
+                      searchmoves.end());
+    if (!searchmoves.empty()) return searchmoves;
+    CERR << "No legal searchmoves. Ignoring!";
```
Comment (Mardak) [inline src/mcts/search.cc:66]: Throwing an exception instead

**Comment by Mardak** [comment]
Makes sense to not add then remove. I suppose the other instances of Search don't pass in moves anyway.
