### PR TITLE
disable max_needed optimization when filtering root moves

### LINKED ISSUE #1595: v0.28rc1 crash upon short search
This simple search crashes v0.28(rc1) on both Linux and Windows (replicated by two people on two systems). The same inputs work fine on v0.27 (and Stockfish does not report any problem with the input position). Note that using 6 man tablebases seems necessary to replicate.
```
lc0  -w d:\weights\lczero.org\weights_run2_744154.pb --syzygy-paths=f:\sygyzy\5and6man

position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves d2d4 g8f6 g1f3 g7g6 c1g5 f8g7 b1d2 d7d5 e2e3 e8g8 c2c3 c7c5 f1e2 c5d4 e3d4 b8c6 e1g1 h7h6 g5f4 g6g5 f4g3 f6e4 d2e4 d5e4 f3d2 f7f5 f2f4 e7e6 d2c4 c6e7 f4g5 h6g5 g3e5 c8d7 d1d2 e7g6 e5d6 f8f7 e2h5 d7b5 h5g6 b5c4 g6f7 g8f7 d6g3 c4f1 a1f1 g7f6 d2e2 f7g6 g3f2 d8d5 c3c4 d5c6 f1d1 a8d8 b2b3 f5f4 d4d5 e6d5 c4d5 c6e8 f2a7 e4e3 a7b6 d8d7 e2d3 g6h6 d3f5 f6c3 d1d3 c3a1 d5d6 e3e2 d3h3 h6g7 f5g5 e8g6 g5g6 g7g6 g1f2 d7d6 b6c7 d6c6 c7f4 c6c2 h3d3 a1c3 d3c3 c2c3 f2e2 c3c2 e2d3 c2a2 f4d2 g6f5 h2h3 a2b2 g2g4 f5e6 d3c3 b2b1 h3h4 b1g1 g4g5 g1h1 c3b4 h1h4 b4b5 h4h3 b3b4 e6d7 g5g6 h3g3 g6g7 g3g7 b5b6 d7c8 b4b5 g7g4 d2c3 g4g6 b6a7 g6g5 a7b6 c8b8 c3d4 g5g6 b6c5 b8c7 d4e5 c7d7 e5c3 d7e7 
go nodes 1000
```

### PR DESCRIPTION
**Pull request by borg323**
Fixes #1595

### CODE REVIEW

File: src/mcts/search.cc [hunk 1]
```diff
@@ -1653,8 +1653,10 @@ void SearchWorker::PickNodesToExtendTask(Node* node, int base_depth,
       // Which we are putting off until after policy is copied so we can create
       // visited policy without having to cache it in the node (allowing the
       // node to stay at 64 bytes).
-      int max_needed = std::min(static_cast<int>(node->GetNumEdges()),
-                                node->GetNStarted() + cur_limit + 2);
+      int max_needed = node->GetNumEdges();
+      if (root_move_filter.empty()) {
```
Comment (Tilps) [inline src/mcts/search.cc:1657]: This should be if (!is_root_move || root_move_filter.empty()) {

**Review by Tilps — APPROVED** [review]
