### PR TITLE
Fix the improper handling of terminal V values. 

### LINKED ISSUE #91: Unexpected Behavior Change With Recent lc0 Versions
Using main net ID 421, with the latest versions of lc0 master (Mon, Jun 18), and the latest crem builds, run the following test position, which is a mate in 1. 

`1. b3 g6 2. Bb2 Nf6 3. g3 Bg7 4. Nf3 c5 5. c4 Nc6 6. Bg2 d6 7. O-O e5 8. Nc3 O-O 9. d3 Rb8 10. Qd2 a6 11. Ng5 h6 12. Nge4 Nh5 13. Nd5 f5 14. Nec3 f4 15. Kh1 Be6 16. Bf3 Nd4 17. Bxh5 gxh5 18. gxf4 Qh4 19. Ne4 exf4 20. Rg1 Kh7 21. Qa5 b6 22. Qxa6 Rf7 23. Nxd6 Rd7 24. Nxb6 Rxd6 25. Rxg7+ Kxg7 26. Qa7+ Bf7 27. Bxd4+ Kh7`

At low node counts ~(0-1000), ID 421 correctly finds the mate in 1 (Qxf7#)
At higher node counts, ~>1000 nodes, ID 421 unfinds the mate in 1 (eventually settles on Qxb8)

On older versions of lc0 (~a few weeks old; I haven't tracked down the exact change at this time), ID 421 finds the mate in 1 and keeps it. This suggests recent changes to lc0 are causing the change.

LCZero v0.10 also finds the mate in 1 and keeps it fine.

I found this position because the incorrect analysis caused Leela to lose a machine match I was running (it moved into the mate-in-1 by playing 27. ...Kh7???).

### PR DESCRIPTION
**Pull request by dubslow**
This is a selective reversion of cda3a4e4281b84ce38a472e99f03e9f57bad7d9f.

Fixes #91.

Credit to Tilps for spotting it. I was reviewing, and would have found it eventually, but it probably would have taken me several hours in my... less than fully awake state right now.

### CODE REVIEW

File: src/mcts/search.cc [hunk 1]
```diff
@@ -880,7 +877,7 @@ void SearchWorker::DoBackupUpdate() {
 // 7. UpdateCounters()
 //~~~~~~~~~~~~~~~~~~~~
 void SearchWorker::UpdateCounters() {
-  search_->UpdateRemainingMoves();  // Updates smart pruning counters.
+  search_->UpdateRemainingMoves(); // Updates smart pruning counters.
```
Comment (Tilps) [inline src/mcts/search.cc]: This change is unrelated.  I believe that this codebase is following google c++ style - and two spaces is the correct whitespace in this scenario under that style guide.

Comment (dubslow) [reply src/mcts/search.cc]: er... why does it say that lol
