### PR TITLE
Fix time reporting issues.

### LINKED ISSUE #1012: Timer doesn't reset on `go` command when there's no `position command`
CrazyKing on discord reported a performance degradation in v0.23 (nps).

Relevant logs are attached.
[leelalog_T40_B260_lc0_23.0.txt](https://github.com/LeelaChessZero/lc0/files/3878726/leelalog_T40_B260_lc0_23.0.txt)
[leelalog_T40_B260_lc0_22.0.txt](https://github.com/LeelaChessZero/lc0/files/3878727/leelalog_T40_B260_lc0_22.0.txt)

[lc0.config.txt](https://github.com/LeelaChessZero/lc0/files/3878738/lc0.config.txt)

### PR DESCRIPTION
**Pull request by mooskagh**
1. Reset move clock on `go` command if there was no ucinewgame or
position before it.
2. For nps, only start timer after the first iteration is done.

Fixes #1012

### CODE REVIEW

File: src/mcts/search.cc [hunk 1]
```diff
@@ -108,9 +108,15 @@ void Search::SendUciInfo() REQUIRES(nodes_mutex_) {
...
-  common_info.tb_hits = tb_hits_.load(std::memory_order_acquire);
+  if (nps_start_time_) {
+    const auto time_since_first_batch_ms =
+        std::chrono::duration_cast<std::chrono::milliseconds>(
+            std::chrono::steady_clock::now() - *nps_start_time_)
+            .count();
+    common_info.nps = total_playouts_ * 1000 / time_since_first_batch_ms;
+  } else {
+    common_info.nps = 0;
+  }
```
Comment (borg323) [inline src/mcts/search.cc]: Here, `time_since_first_batch_ms` may be zero - e.g. by doing `go nodes 100` twice.  Suggested patch:
```diff
diff --git a/src/mcts/search.cc b/src/mcts/search.cc
index 6772688..a233de0 100644
--- a/src/mcts/search.cc
+++ b/src/mcts/search.cc
@@ -113,9 +113,9 @@ void Search::SendUciInfo() REQUIRES(nodes_mutex_) {
         std::chrono::duration_cast<std::chrono::milliseconds>(
             std::chrono::steady_clock::now() - *nps_start_time_)
             .count();
-    common_info.nps = total_playouts_ * 1000 / time_since_first_batch_ms;
-  } else {
-    common_info.nps = 0;
+    if (time_since_first_batch_ms > 0) {
+      common_info.nps = total_playouts_ * 1000 / time_since_first_batch_ms;
+    }
   }
 
   int multipv = 0;
```
This way nps is not reported if unknown. The last else is also removed to do the same when `nps_start_time_` is still unset.

Comment (mooskagh) [reply src/mcts/search.cc]: Done.

File: src/mcts/search.cc [hunk 2]
```diff
@@ -108,9 +108,15 @@ void Search::SendUciInfo() REQUIRES(nodes_mutex_) {
   }
   common_info.hashfull =
       cache_->GetSize() * 1000LL / std::max(cache_->GetCapacity(), 1);
-  common_info.nps =
-      common_info.time ? (total_playouts_ * 1000 / common_info.time) : 0;
-  common_info.tb_hits = tb_hits_.load(std::memory_order_acquire);
```
Comment (Mardak) [inline src/mcts/search.cc]: This `tb_hits` removal was probably unintentional?

Comment (mooskagh) [reply src/mcts/search.cc]: Indeed it was! Returned it back.
