### PR TITLE
Convert moves to FRC-compatible encoding when building searchmoves list.

### LINKED ISSUE #1001: Crash when "go … searchmoves" for non FRC-style e1c1/e1g1 castling
```
position startpos moves e2e4 e7e6 d2d4 d7d5 c1e3 d5e4 b1d2 g8f6 c2c3 f8e7 d1c2 f6d5 d2e4 f7f5 e4g3 f5f4 e3d2 f4g3 h2g3 g7g6

go nodes 1 searchmoves e1c1
…
bestmove a1a1

go nodes 1 searchmoves e1c1
Segmentation fault: 11
```

To be clear, using e1c1 as part of `position … moves … e1c1` works fine.

### PR DESCRIPTION
**Pull request by mooskagh**
(also do that when unvisited move is entered through uci position command, but it worked fine without that too)

Fixes #1001

### CODE REVIEW

File: src/chess/board.cc [hunk 1]
```diff
@@ -759,6 +759,13 @@ Move ChessBoard::GetLegacyMove(Move move) const {
   return move;
 }
 
+Move ChessBoard::GetModernMove(Move move) const {
+  if (our_king_ != E1 || move.from() != E1) return move;
+  if (move == Move(E1, G1) && !our_pieces_.get(G1)) return Move(E1, H1);
```
Comment (borg323) [inline src/chess/board.cc]: Is the `&& !our_pieces_.get(G1)` part needed?

File: src/chess/board.cc [hunk 2]
```diff
@@ -759,6 +759,13 @@ Move ChessBoard::GetLegacyMove(Move move) const {
...
+  if (move == Move(E1, C1) && !our_pieces_.get(C1)) return Move(E1, A1);
```
Comment (borg323) [inline src/chess/board.cc]: Same here

File: src/chess/board.cc (hunk 1 above)
Comment (mooskagh) [reply src/chess/board.cc]: Yes, if there is a rook at G1, then it's already "modern-style" move and should not be converted.

File: src/chess/board.h [hunk 3]
```diff
@@ -101,6 +101,8 @@ class ChessBoard {
   bool IsSameMove(Move move1, Move move2) const;
   // Returns the same move but with castling encoded in legacy way.
   Move GetLegacyMove(Move move) const;
+  // Returns the same move but with castling encoded in modern 😎 way.
```
Comment (borg323) [inline src/chess/board.h]: Maybe remove the smiley? Since it is outside the Unicode BMP, I can see it causing issues with some tools.

File: src/engine.cc [hunk 4]
```diff
@@ -61,10 +61,12 @@ const OptionId kShowWDL{"show-wdl", "UCI_ShowWDL",
                         "Show win, draw and lose probability."};
 
 MoveList StringsToMovelist(const std::vector<std::string>& moves,
-                           bool is_black) {
+                           const ChessBoard& board) {
   MoveList result;
   result.reserve(moves.size());
-  for (const auto& move : moves) result.emplace_back(move, is_black);
+  for (const auto& move : moves) {
+    result.push_back(board.GetModernMove({move, board.flipped()}));
```
Comment (borg323) [inline src/engine.cc]: Is there a reason for the change to `push_back`?

Comment (mooskagh) [reply src/engine.cc]: Probably there's no difference in this case, but my thoughts were that there would be only one construction of Move (inside GetModernMove()) due to RVO, but with emplace_back I was not sure.

UPD. I've just checked on godbolt and indeed they generate identical code in this case, changing to emplace_back.
