### PR TITLE
Remove use of popcnt, fixes #174.

### LINKED ISSUE #174: Crash with blas backend on Core 2 Duo
There were several crashes observed with the blas backend under windows on Core2 Duo processors, and this is a reliable way to reproduce: `lc0 -w weights_490.txt.gz --minibatch-size=4 --threads=2 --cpuct=1.2 --policy-softmax-temp=1 --fpu-reduction=.2 --max-prefetch=0` enter `position startpos moves f2f4 d7d5 e2e3 c7c5 b2b3 g7g6 c1b2 g8f6 f1b5 c8d7 b5d7 d8d7 g1f3 f8g7 e1g1 e8g8 f3e5 d7c7 d1e2 b8c6 b1a3 f6e4 d2d3 e4d6 c2c4 d5c4 b3c4 a7a6 e5c6 g7b2 e2b2 c7c6 e3e4 b7b5 b2f2 b5c4 e4e5 d6f5 a3c4 f8d8 g2g4 f5g7 f2g3 d8d4 a1e1 a8d8 e1e3 h7h5 e5e6 f7f6 g4h5 g6h5 f1f2 h5h4 g3g4 d8d5 c4e5 c6e6 g4e6 g7e6 e5c6 g8f7 c6d4 e6d4 f2f1 d4f5 e3f3 f5d4 f3h3 d4f5 f1c1 f7g6 g1f2 g6h5 h3f3 f5d4 f3e3 d4f5 e3e1 d5d3 c1c5 h5g4 f2e2 d3e3 e2d2 e3f3 c5a5 f3f2 e1e2 f2f4 a5a6 h4h3 d2d3 f4f3 d3c4 f5d6 c4c5 f3c3 c5b4 c3c7 a2a4 f6f5 a4a5 f5f4 a6a8 g4f3 e2a2 e7e5 a2a3 f3g2 a5a6 c7c4 b4b3` and `go`. It happens after about 10000 nodes.

This was observed using several different lc0 binaries, both self compiled ()VS2017) and from Appveyor (VS2015). The binaries tested were 5 different versions from July 8 up to July 13, all crashing. Both openblas and MKL builds were affected. 

I was able to catch the crash under gdb:
```
info depth 3 seldepth 40 time 417327 nodes 8252 score cp -237 hashfull 30 nps 19 pv c4c8 a8c8 d6c8 a3a2 g2g1 a2c2 c8a7 c2c7 a7b5 c7g7 g1h2 b3c4 b5d6 c4d5 d6e8 a6a7 e8g7 a7a8q h2g3 a8g8 h3h2 g8g7 g3f2 g7h6 f2g1 h6g5 g1f2 g5h4 f2g2 h4g4 g2f2 g4h3 f2g1 h3g4 g1f2 g4h3 f2g1 h3g4 g1f2
info depth 3 seldepth 40 time 422531 nodes 8350 score cp -237 hashfull 30 nps 19 pv c4c8 a8c8 d6c8 a3a2 g2g1 a2c2 c8a7 c2c7 a7b5 c7g7 g1h2 b3c4 b5d6 c4d5 d6e8 a6a7 e8g7 a7a8q h2g3 a8g8 h3h2 g8g7 g3f2 g7h6 f2g1 h6g5 g1f2 g5h4 f2g2 h4g4 g2f2 g4h3 f2g1 h3g4 g1f2 g4h3 f2g1 h3g4 g1f2
info depth 3 seldepth 40 time 427728 nodes 8443 score cp -236 hashfull 30 nps 19 pv c4c8 a8c8 d6c8 a3a2 g2g1 a2c2 c8a7 c2c7 a7b5 c7g7 g1h2 b3c4 b5d6 c4d5 d6e8 a6a7 e8g7 a7a8q h2g3 a8g8 h3h2 g8g7 g3f2 g7h6 f2g1 h6g5 g1f2 g5h4 f2g2 h4g4 g2f2 g4h3 f2g1 h3g4 g1f2 g4h3 f2g1 h3g4 g1f2

Program received signal SIGILL, Illegal instruction.
[Switching to Thread 7068.0x704]
0x000000013f376864 in ?? ()
```

This has been reproduced under windows with the following CPUs:
* Core2 Duo E8400 @ 3.00GHz 
* Core2 Duo T7250 @ 2.00GHz

It wasn't observed under linux on a Core i5-4590 @ 3.30GHz (or with windows under virtualbox on same CPU), or from the start position with same command line for ~300000 nodes.

### PR DESCRIPTION
**Pull request by borg323**
The popcnt instruction is not supported on older core processors. The fact that even on those this is only rarely encountered shows this is not a speed critical piece of code. However since it was used just to check for less than 4 pieces on the board, the replacement code can be very efficient. Microbenchmarks show the new code to be slightly faster than a single popcnt call, but it replaces two of them so it should be a win regardless.

### CODE REVIEW

File: src/chess/board.cc [hunk 1]
```diff
@@ -709,14 +709,14 @@ bool ChessBoard::HasMatingMaterial() const {
...
-  int their = _mm_popcnt_u64(their_pieces_.as_int());
-#else
-  int our = __builtin_popcountll(our_pieces_.as_int());
-  int their = __builtin_popcountll(their_pieces_.as_int());
-#endif
-  if (our + their < 4) {
+  // All the pieces together.
+  uint64_t x = our_pieces_.as_int() | their_pieces_.as_int();
+  // x &= x - 1 clears the rigthmost set bit (if any).
+  x &= x - 1;
```
Comment (DanielUranga) [inline src/chess/board.cc]: maybe this can be done in a small for-loop to make  it look nicer.
